# Generated by Django 5.2 on 2025-04-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Organization',
        ),
    ]
