# Generated by Django 5.2 on 2025-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_user_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='password_hash',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='username',
        ),
        migrations.AddField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
            preserve_default=False,
        ),
    ]
