# Generated by Django 5.2 on 2025-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
