# Generated by Django 5.2 on 2025-04-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='amount_gathered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
