# Generated by Django 5.2 on 2025-05-06 17:23

import django.core.validators
import django.db.models.deletion
import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_campaign_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.campaign_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='OrgReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organization.organization')),
            ],
        ),
    ]
