# Generated by Django 5.2 on 2025-05-13 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_campaign_images_orgreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Goal amount must be greater than 0')]),
        ),
    ]
